version: '3.9'

services:
  ultrawealth:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NEXT_PUBLIC_TURINGOS_API: 'http://localhost:9999'
    restart: unless-stopped
